import type { Category } from "@/types";

// ─────────────────────────────────────────────
// ADMIN KEYWORD GUIDE
// Each category has an `id` field — this is the
// keyword used in the admin panel to reference it.
// ─────────────────────────────────────────────

const categoriesData: Category[] = [
  {
    id: "yogistaan_academy",
    description: "Structured programs for beginners to advanced learners who want to master yoga and become certified instructors.",
    name: "Yogistaan Academy",
    type: "academy",
    active: true,
    slug: "yoga",
    bannerImage: "/banner/banner1.png",
    items: [
      {
        id: 1,
        title: "Beginner Bliss 10 Days 100 Hrs YTTC",
        image: "/category/rishi.jpg",
        price: 15000,
        location: "Rishikesh",
        duration: "10 Days",
        places: ["Beginner", "Yoga", "Certification"],
        slug: "beginner-bliss-100hrs-yttc",
      },
      {
        id: 2,
        title: "Beyond to Basics 28 Days 200 Hrs YTTC",
        image: "/category/rishi2.jpg",
        price: 30000,
        location: "Rishikesh",
        duration: "28 Days",
        places: ["Intermediate", "Yoga Training"],
        slug: "beyond-to-basics-200hrs-yttc",
      },
      {
        id: 3,
        title: "Basic to Moderate Yoga Bliss 40 Days 300 Hrs",
        image: "/category/goa.jpg",
        price: 45000,
        location: "Goa",
        duration: "40 Days",
        places: ["Advanced", "Lifestyle"],
        slug: "basic-to-moderate-300hrs-yttc",
      },
      {
        id: 4,
        title: "Moderate to Advance Yoga 60 Days 500 Hrs",
        image: "/category/kerela.jpg",
        price: 60000,
        location: "Kerala",
        duration: "60 Days",
        places: ["Mastery", "Deep Practice"],
        slug: "moderate-to-advance-500hrs-yttc",
      },
      {
        id: 5,
        title: "Ultra Advance Solar Power Yoga 60 Days",
        image: "/category/hima.jpg",
        price: 80000,
        location: "Himalayas",
        duration: "60 Days",
        places: ["Energy", "Spiritual Growth"],
        slug: "ultra-advance-solar-yoga",
      },
    ],
  },
  {
    id: "d_retreats",
    description: "Peaceful getaway experiences focused on yoga, meditation, and inner healing in serene natural environments.",
    name: "D Retreats (Deep Discovery Retreats)",
    type: "retreat",
    active: true,
    slug: "retreat",
    bannerImage: "/banner/banner2.png",
    items: [
      {
        id: 6,
        title: "5 Days Shantam Chittam Retreat",
        image: "/category/rishi3.jpg",
        price: 20000,
        location: "Rishikesh",
        duration: "5 Days",
        places: ["Peace", "Healing"],
        slug: "shantam-chittam-retreat",
      },
      {
        id: 7,
        title: "4 Days OM Retreat (Omniscient Meditation)",
        image: "/category/rishi4.jpg",
        price: 18000,
        location: "Rishikesh",
        duration: "4 Days",
        places: ["Meditation", "Awareness"],
        slug: "om-retreat",
      },
      {
        id: 8,
        title: "7 Days The Clarity Retreat",
        image: "/category/hima2.jpg",
        price: 25000,
        location: "Himalayas",
        duration: "7 Days",
        places: ["Clarity", "Mindfulness"],
        slug: "clarity-retreat",
      },
      {
        id: 9,
        title: "7 Days The Ecstatic Feminine",
        image: "/category/goa2.jpg",
        price: 27000,
        location: "Goa",
        duration: "7 Days",
        places: ["Feminine Energy", "Healing"],
        slug: "ecstatic-feminine",
      },
      {
        id: 10,
        title: "6 Days Pokhara Himalayan Retreat",
        image: "/category/nepal.jpg",
        price: 30000,
        location: "Nepal",
        duration: "6 Days",
        places: ["Nature", "Silence"],
        slug: "pokhara-retreat",
      },
    ],
  },
  {
    id: "spiritual_adventure",
    description: "A blend of thrill and spirituality combining outdoor exploration with mindfulness and self-discovery.",
    name: "Spiritual Adventure Programs",
    type: "adventure",
    active: true,
    slug: "spiritual",
    bannerImage: "/banner/banner3.png",
    items: [
      {
        id: 12,
        title: "8 Days Kedarkantha Trek Expedition",
        image: "/category/hima.jpg",
        price: 15000,
        location: "Uttarakhand",
        duration: "8 Days",
        places: ["Trek"],
        slug: "kedarkantha-trek",
      },
      {
        id: 13,
        title: "15 Days Gangotri to Kedarnath Trek",
        image: "/category/mathura.jpg",
        price: 40000,
        location: "Himalayas",
        duration: "15 Days",
        places: ["Survival"],
        slug: "gangotri-kedarnath",
      },
      {
        id: 14,
        title: "15 Days Everest Base Camp Trek",
        image: "/category/nepal.jpg",
        price: 90000,
        location: "Nepal",
        duration: "15 Days",
        places: ["Extreme"],
        slug: "everest-basecamp",
      },
      {
        id: 15,
        title: "8 Days Manali to Leh Bike Ride",
        image: "/category/hima2.jpg",
        price: 35000,
        location: "Ladakh",
        duration: "8 Days",
        places: ["Bike"],
        slug: "manali-leh",
      },
      {
        id: 16,
        title: "9 Days Delhi to Spiti Bike Ride",
        image: "/category/hima.jpg",
        price: 38000,
        location: "Spiti Valley",
        duration: "9 Days",
        places: ["Bike"],
        slug: "delhi-spiti",
      },
      {
        id: 17,
        title: "3 Days Mumbai to Goa Ride",
        image: "/category/kerela.jpg",
        price: 12000,
        location: "Goa",
        duration: "3 Days",
        places: ["Road Trip"],
        slug: "mumbai-goa",
      },
    ],
  },
  {
    id: "d_fest",
    name: "D Fest (Divine Dive Festival)",
    description: "Exciting festivals celebrating spirituality, music, and community.",
    type: "fest",
    active: true,
    slug: "divine",
    bannerImage: "/banner/banner4.png",
    items: [
      {
        id: 18,
        title: "5 Days Free Yoga Festival",
        image: "/category/goa.jpg",
        price: 5000,
        location: "Rishikesh & Goa",
        duration: "5 Days",
        places: ["Festival"],
        slug: "yoga-festival",
      },
      {
        id: 19,
        title: "4 Days Full Moon Party",
        image: "/category/moon.jpg",
        price: 8000,
        location: "Goa",
        duration: "4 Days",
        places: ["Party"],
        slug: "full-moon",
      },
      {
        id: 20,
        title: "3 Days New Year Party",
        image: "/category/year.jpg",
        price: 10000,
        location: "Goa",
        duration: "3 Days",
        places: ["New Year"],
        slug: "new-year",
      },
      {
        id: 21,
        title: "3 Days Holi Celebration",
        image: "/category/holi.jpg",
        price: 10000,
        location: "Mathura",
        duration: "3 Days",
        places: ["Holi"],
        slug: "holi-retreat",
      },
    ],
  },
  {
    id: "d_tirth",
    name: "D Tirth (Dharma Tirth)",
    description: "Spiritual pilgrimages to sacred sites across India and beyond for deepening one's spiritual journey.",
    type: "tirth",
    active: true,
    slug: "dharma",
    bannerImage: "/banner/banner5.png",
    items: [
      {
        id: 22,
        title: "4 Days Spiritual Wandering Sadhna",
        image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773",
        price: 15000,
        location: "India",
        duration: "4 Days",
        places: ["Spiritual", "Journey"],
        slug: "wandering-sadhna",
      },
      {
        id: 23,
        title: "7 Days Char Dham Sadhna",
        image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220",
        price: 35000,
        location: "Uttarakhand",
        duration: "7 Days",
        places: ["Pilgrimage"],
        slug: "char-dham",
      },
      {
        id: 24,
        title: "7 Days Kailash Mansarovar Yatra",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
        price: 120000,
        location: "Tibet",
        duration: "7 Days",
        places: ["Sacred", "Adventure"],
        slug: "kailash-yatra",
      },
      {
        id: 25,
        title: "7 Days Kashmir Tirth Sadhna",
        image: "/category/jammu.jpg",
        price: 45000,
        location: "Jammu & Kashmir",
        duration: "7 Days",
        places: ["Tirth"],
        slug: "kashmir-tirth",
      },
    ],
  }
];

export default categoriesData;

export const CATEGORIES = [
    {
        title: "Yoga Teacher Training",
        slug: "yoga",
        description:
            "Structured programs designed for beginners to advanced learners who want to master yoga practices and become certified instructors.",
        img: "/image1.jpg",
    },
    {
        title: "Retreats & Relaxation",
        slug: "retreat",
        description:
            "Peaceful getaway experiences focused on yoga, meditation, and inner healing in serene natural environments.",
        img: "/image3.jpg",
    },
    {
        title: "Spiritual Adventures",
        slug: "spiritual",
        description:
            "A blend of thrill and spirituality combining outdoor exploration with mindfulness and self-discovery.",
        img: "/image4.jpg",
    },
    {
        title: "Divine Festivals",
        slug: "divine",
        description:
            "Celebration-based gatherings with music, yoga, and spiritual energy that bring people together in joy.",
        img: "/image1.jpg",
    },
    {
        title: "Dharma & Pilgrimage",
        slug: "dharma",
        description:
            "Sacred journeys to spiritual destinations focused on devotion, tradition, and inner connection.",
        img: "https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&auto=format&fit=crop&q=80",
    },
];
