export interface StoreProduct {
  id: number;
  title: string;
  image: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviews: number;
  badge: string | null;
  slug: string;
  category: string;
  description: string;
  features: string[];
  inStock: boolean;
  images: string[];
}

export const storeData: StoreProduct[] = [
 {
  id: 31,
  title: "Cork Yoga Block Set (2 pcs)",
  image: "/store/blocks.jpg",
  price: 1200,
  originalPrice: 1500,
  rating: 4.6,
  reviews: 85,
  badge: "Bestseller",
  slug: "cork-yoga-block-set",
  category: "Props",
  description: "Premium cork yoga blocks for stability, balance, and deeper stretches.",
  features: ["Set of 2", "Eco-friendly cork", "Non-slip grip"],
  inStock: true,
  images: [],
},
{
  id: 32,
  title: "Yoga Strap Cotton 8ft",
  image: "/store/strap.jpg",
  price: 450,
  originalPrice: 600,
  rating: 4.4,
  reviews: 52,
  badge: null,
  slug: "yoga-strap-8ft",
  category: "Props",
  description: "Durable cotton strap for flexibility and alignment support.",
  features: ["8ft length", "Metal buckle", "Soft cotton"],
  inStock: true,
  images: [],
},
{
  id: 34,
  title: "High-Waist Yoga Leggings",
  image: "/store/leggis.jpg",
  price: 1800,
  originalPrice: 2400,
  rating: 4.5,
  reviews: 110,
  badge: "Trending",
  slug: "yoga-leggings",
  category: "Apparel",
  description: "Stretchable, breathable leggings designed for flexibility.",
  features: ["4-way stretch", "Sweat resistant", "High waist fit"],
  inStock: true,
  images: [],
},
{
  id: 36,
  title: "Yoga Hoodie",
  image: "/store/hoddies.jpg",
  price: 2200,
  originalPrice: 2800,
  rating: 4.6,
  reviews: 70,
  badge: "New",
  slug: "yoga-hoodie",
  category: "Apparel",
  description: "Comfortable hoodie for pre/post yoga sessions.",
  features: ["Soft cotton", "Warm & breathable"],
  inStock: true,
  images: [],
},

{
  id: 37,
  title: "Ayurvedic Chyawanprash",
  image: "/store/chyavanprash.jpg",
  price: 900,
  originalPrice: 1200,
  rating: 4.7,
  reviews: 140,
  badge: "Organic",
  slug: "chyawanprash",
  category: "Supplements",
  description: "Traditional immunity booster with Ayurvedic herbs.",
  features: ["Boost immunity", "Natural herbs"],
  inStock: true,
  images: [],
},
{
  id: 38,
  title: "Herbal Sleep Support Capsules",
  image: "/store/sleeping-bag.jpg",
  price: 1100,
  originalPrice: 1400,
  rating: 4.3,
  reviews: 55,
  badge: null,
  slug: "sleep-support",
  category: "Supplements",
  description: "Helps improve sleep quality naturally.",
  features: ["Ashwagandha", "Calming herbs"],
  inStock: true,
  images: [],
},
{
  id: 39,
  title: "Organic Protein Powder",
  image: "/store/protein-powder.jpg",
  price: 1800,
  originalPrice: 2200,
  rating: 4.5,
  reviews: 90,
  badge: "Fitness",
  slug: "organic-protein",
  category: "Supplements",
  description: "Plant-based protein for recovery and strength.",
  features: ["Vegan", "No additives"],
  inStock: true,
  images: [],
},

{
  id: 40,
  title: "Trekking Backpack 60L",
  image: "/store/tracking_bag.jpg",
  price: 3500,
  originalPrice: 4200,
  rating: 4.6,
  reviews: 88,
  badge: "Top Rated",
  slug: "trekking-backpack",
  category: "Adventure",
  description: "Durable backpack for trekking and expeditions.",
  features: ["60L capacity", "Water resistant"],
  inStock: true,
  images: [],
},
{
  id: 41,
  title: "Portable Camping Tent",
  image: "/store/tent.jpg",
  price: 4500,
  originalPrice: 5200,
  rating: 4.5,
  reviews: 60,
  badge: null,
  slug: "camping-tent",
  category: "Adventure",
  description: "Lightweight tent for outdoor camping.",
  features: ["2-person", "Waterproof"],
  inStock: true,
  images: [],
},
{
  id: 42,
  title: "Sleeping Bag (All Weather)",
  image: "/store/sleeping-bag.jpg",
  price: 2500,
  originalPrice: 3000,
  rating: 4.4,
  reviews: 48,
  badge: null,
  slug: "sleeping-bag",
  category: "Adventure",
  description: "Comfortable sleeping bag for all weather conditions.",
  features: ["Thermal insulation", "Compact"],
  inStock: true,
  images: [],
},
];